services:
  - type: web
    name: real-time-object-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 # Stable version for deployment
